In [1]:
import numpy as np
import pandas as pd

## import dataset

In [2]:
df=pd.read_csv("/home/student/Downloads/housing.csv")

## understand the dataset

In [3]:
df.shape #(rows,columns)

(25731, 19)

In [4]:
df.columns #col names in the dataset

Index(['price', 'bedrooms', 'bathrooms', 'livingArea', 'lotSize', 'yearBuilt',
       'propertyTaxRate', 'taxAssessedValue', 'zestimate', 'rentZestimate',
       'latitude', 'longitude', 'resoFacts/stories', 'resoFacts/hasGarage',
       'resoFacts/hasHeating', 'resoFacts/hasCooling',
       'resoFacts/hasFireplace', 'resoFacts/isNewConstruction', 'homeType'],
      dtype='str')

In [5]:
df.head() #first 5 rows

,price,bedrooms,bathrooms,livingArea,lotSize,yearBuilt,propertyTaxRate,taxAssessedValue,zestimate,rentZestimate,latitude,longitude,resoFacts/stories,resoFacts/hasGarage,resoFacts/hasHeating,resoFacts/hasCooling,resoFacts/hasFireplace,resoFacts/isNewConstruction,homeType
0,315400,3.0,3.0,1806.0,1555.0,2007.0,1.12,273960.0,317406.0,1950.0,45.543571,-122.441765,NaN,False,True,False,True,NaN,TOWNHOUSE
1,400000,3.0,3.0,1518.0,3484.0,2001.0,1.12,NaN,NaN,NaN,45.547585,-122.453224,2.0,False,True,True,True,False,SINGLE_FAMILY
2,512000,4.0,3.0,2724.0,9583.0,1982.0,1.12,397560.0,512355.0,1995.0,45.488228,-122.444420,2.0,False,True,True,True,False,SINGLE_FAMILY
3,348000,3.0,1.0,1217.0,13939.0,1953.0,1.12,269520.0,NaN,1695.0,45.526634,-122.464088,1.0,False,True,NaN,True,False,SINGLE_FAMILY
4,510000,6.0,3.0,2400.0,8545.0,1967.0,1.12,421980.0,NaN,1395.0,45.511238,-122.431534,NaN,False,True,True,NaN,NaN,APARTMENT

In [6]:
df.tail() #last 5 rows

,price,bedrooms,bathrooms,livingArea,lotSize,yearBuilt,propertyTaxRate,taxAssessedValue,zestimate,rentZestimate,latitude,longitude,resoFacts/stories,resoFacts/hasGarage,resoFacts/hasHeating,resoFacts/hasCooling,resoFacts/hasFireplace,resoFacts/isNewConstruction,homeType
25726,415000,3.0,2.0,1378.0,10018.0,1977.0,1.13,386050.0,489400.0,2495.0,45.465111,-122.808701,1.0,False,True,True,True,False,SINGLE_FAMILY
25727,615000,4.0,3.0,2176.0,9583.0,1974.0,1.13,447330.0,725500.0,2495.0,45.467197,-122.829628,3.0,False,True,True,True,False,SINGLE_FAMILY
25728,380000,2.0,2.0,1466.0,1742.0,2001.0,1.13,NaN,387200.0,2131.0,NaN,NaN,2.0,True,True,True,True,False,TOWNHOUSE
25729,57997,3.0,2.0,1450.0,17859.0,1920.0,1.13,370770.0,563700.0,2564.0,45.467545,-122.748367,NaN,False,True,False,False,NaN,SINGLE_FAMILY
25730,585000,4.0,3.0,2615.0,15681.0,1959.0,1.13,554140.0,682500.0,3521.0,45.471767,-122.746880,2.0,False,True,NaN,True,False,SINGLE_FAMILY

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25731 entries, 0 to 25730
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   price                        25731 non-null  int64
 1   bedrooms                     24961 non-null  float64
 2   bathrooms                    25247 non-null  float64
 3   livingArea                   25266 non-null  float64
 4   lotSize                      22841 non-null  float64
 5   yearBuilt                    25185 non-null  float64
 6   propertyTaxRate              25720 non-null  float64
 7   taxAssessedValue             24337 non-null  float64
 8   zestimate                    23757 non-null  float64
 9   rentZestimate                24826 non-null  float64
 10  latitude                     25718 non-null  float64
 11  longitude                    25718 non-null  float64
 12  resoFacts/stories            21206 non-null  float64
 13  resoFacts/hasGarage          25731 non-null  bool
 14  resoFacts/hasHeating         25730 non-null  object
 15  resoFacts/hasCooling         21235 non-null  object
 16  resoFacts/hasFireplace       21107 non-null  object
 17  resoFacts/isNewConstruction  21374 non-null  object
 18  homeType                     25731 non-null  str
dtypes: bool(1), float64(12), int64(1), object(4), str(1)
memory usage: 3.6+ MB

In [8]:
df.describe()

,price,bedrooms,bathrooms,livingArea,lotSize,yearBuilt,propertyTaxRate,taxAssessedValue,zestimate,rentZestimate,latitude,longitude,resoFacts/stories
count,2.573100e+04,24961.000000,25247.000000,25266.000000,2.284100e+04,25185.000000,25720.000000,2.433700e+04,2.375700e+04,24826.000000,25718.000000,25718.000000,21206.000000
mean,5.851917e+05,3.356356,2.561896,2179.079237,2.740146e+04,1975.062140,1.114860,4.932501e+05,6.441574e+05,2836.253363,45.478251,-122.686321,1.985429
std,4.518907e+05,1.001626,1.009135,1129.151916,1.391282e+06,54.205158,0.019895,6.905081e+05,3.500689e+05,1296.661197,0.065477,0.144860,0.719863
min,3.000000e+02,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.000000e+02,9.170000e+04,916.000000,45.258659,-123.074242,1.000000
25%,3.910000e+05,3.000000,2.000000,1460.000000,4.791000e+03,1954.000000,1.120000,3.299100e+05,4.495000e+05,2166.000000,45.433972,-122.806112,1.000000
50%,5.220000e+05,3.000000,3.000000,1996.000000,6.969000e+03,1981.000000,1.120000,4.263300e+05,5.737000e+05,2545.000000,45.488914,-122.674080,2.000000
75%,6.622000e+05,4.000000,3.000000,2670.000000,1.001800e+04,2003.000000,1.130000,5.628100e+05,7.259000e+05,3150.000000,45.526379,-122.592539,2.000000
max,4.100000e+07,43.000000,23.000000,51290.000000,2.087221e+08,2021.000000,1.130000,9.500545e+07,6.537500e+06,27029.000000,45.713860,-122.280975,7.000000

## missing values

In [9]:
df.isnull()

,price,bedrooms,bathrooms,livingArea,lotSize,yearBuilt,propertyTaxRate,taxAssessedValue,zestimate,rentZestimate,latitude,longitude,resoFacts/stories,resoFacts/hasGarage,resoFacts/hasHeating,resoFacts/hasCooling,resoFacts/hasFireplace,resoFacts/isNewConstruction,homeType
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False
1,False,False,False,False,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25726,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25727,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25728,False,False,False,False,False,False,False,True,False,False,True,True,False,False,False,False,False,False,False
25729,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False
25730,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [10]:
df.isnull().sum() #col wise null count

price                             0
bedrooms                        770
bathrooms                       484
livingArea                      465
lotSize                        2890
yearBuilt                       546
propertyTaxRate                  11
taxAssessedValue               1394
zestimate                      1974
rentZestimate                   905
latitude                         13
longitude                        13
resoFacts/stories              4525
resoFacts/hasGarage               0
resoFacts/hasHeating              1
resoFacts/hasCooling           4496
resoFacts/hasFireplace         4624
resoFacts/isNewConstruction    4357
homeType                          0
dtype: int64

In [11]:
#few nulls as comapared to 25731.so, we can fill nulls

In [15]:
df.dtypes

price                            int64
bedrooms                       float64
bathrooms                      float64
livingArea                     float64
lotSize                        float64
yearBuilt                      float64
propertyTaxRate                float64
taxAssessedValue               float64
zestimate                      float64
rentZestimate                  float64
latitude                       float64
longitude                      float64
resoFacts/stories              float64
resoFacts/hasGarage               bool
resoFacts/hasHeating            object
resoFacts/hasCooling            object
resoFacts/hasFireplace          object
resoFacts/isNewConstruction     object
homeType                           str
dtype: object

In [12]:
#filling int/float cols with median..,

num_col=df.select_dtypes(include=['int','float']).columns
df[num_col]=df[num_col].fillna(df[num_col].median())

In [13]:
#obj col nulls -> false
obj_col=['resoFacts/hasHeating','resoFacts/hasCooling','resoFacts/hasFireplace','resoFacts/isNewConstruction']
df[obj_col]=df[obj_col].fillna(False)

In [32]:
df[obj_col]=df[obj_col].replace({True:1,False:0})

In [14]:
df.isnull().sum() #nulls filled

price                          0
bedrooms                       0
bathrooms                      0
livingArea                     0
lotSize                        0
yearBuilt                      0
propertyTaxRate                0
taxAssessedValue               0
zestimate                      0
rentZestimate                  0
latitude                       0
longitude                      0
resoFacts/stories              0
resoFacts/hasGarage            0
resoFacts/hasHeating           0
resoFacts/hasCooling           0
resoFacts/hasFireplace         0
resoFacts/isNewConstruction    0
homeType                       0
dtype: int64

## changing datatype

In [15]:
df.dtypes

price                            int64
bedrooms                       float64
bathrooms                      float64
livingArea                     float64
lotSize                        float64
yearBuilt                      float64
propertyTaxRate                float64
taxAssessedValue               float64
zestimate                      float64
rentZestimate                  float64
latitude                       float64
longitude                      float64
resoFacts/stories              float64
resoFacts/hasGarage               bool
resoFacts/hasHeating            object
resoFacts/hasCooling            object
resoFacts/hasFireplace          object
resoFacts/isNewConstruction     object
homeType                           str
dtype: object

In [16]:
#obj,bool to int
df[obj_col]=df[obj_col].astype(int)
df['resoFacts/hasGarage']=df['resoFacts/hasGarage'].astype(int)

In [17]:
df.dtypes

price                            int64
bedrooms                       float64
bathrooms                      float64
livingArea                     float64
lotSize                        float64
yearBuilt                      float64
propertyTaxRate                float64
taxAssessedValue               float64
zestimate                      float64
rentZestimate                  float64
latitude                       float64
longitude                      float64
resoFacts/stories              float64
resoFacts/hasGarage              int64
resoFacts/hasHeating             int64
resoFacts/hasCooling             int64
resoFacts/hasFireplace           int64
resoFacts/isNewConstruction      int64
homeType                           str
dtype: object

## Final Check

In [18]:
df.isnull().sum()

price                          0
bedrooms                       0
bathrooms                      0
livingArea                     0
lotSize                        0
yearBuilt                      0
propertyTaxRate                0
taxAssessedValue               0
zestimate                      0
rentZestimate                  0
latitude                       0
longitude                      0
resoFacts/stories              0
resoFacts/hasGarage            0
resoFacts/hasHeating           0
resoFacts/hasCooling           0
resoFacts/hasFireplace         0
resoFacts/isNewConstruction    0
homeType                       0
dtype: int64

In [19]:
df.dtypes

price                            int64
bedrooms                       float64
bathrooms                      float64
livingArea                     float64
lotSize                        float64
yearBuilt                      float64
propertyTaxRate                float64
taxAssessedValue               float64
zestimate                      float64
rentZestimate                  float64
latitude                       float64
longitude                      float64
resoFacts/stories              float64
resoFacts/hasGarage              int64
resoFacts/hasHeating             int64
resoFacts/hasCooling             int64
resoFacts/hasFireplace           int64
resoFacts/isNewConstruction      int64
homeType                           str
dtype: object

In [42]:
df.describe()

,price,bedrooms,bathrooms,livingArea,lotSize,yearBuilt,propertyTaxRate,taxAssessedValue,zestimate,rentZestimate,latitude,longitude,resoFacts/stories,resoFacts/hasGarage,resoFacts/hasHeating,resoFacts/hasCooling,resoFacts/hasFireplace,resoFacts/isNewConstruction
count,2.573100e+04,25731.000000,25731.000000,25731.000000,2.573100e+04,25731.000000,25731.000000,2.573100e+04,2.573100e+04,25731.000000,25731.000000,25731.000000,25731.000000,25731.000000,25731.000000,25731.000000,25731.000000,25731.000000
mean,5.851917e+05,3.345692,2.570137,2175.770705,2.510657e+04,1975.188139,1.114863,4.896246e+05,6.387521e+05,2826.009522,45.478257,-122.686315,1.987991,0.045082,0.970503,0.716645,0.775835,0.054020
std,4.518907e+05,0.988391,1.001369,1119.167981,1.310837e+06,53.633775,0.019891,6.717133e+05,3.368946e+05,1274.782980,0.065461,0.144824,0.653529,0.207488,0.169200,0.450636,0.417040,0.226062
min,3.000000e+02,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.000000e+02,9.170000e+04,916.000000,45.258659,-123.074242,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.910000e+05,3.000000,2.000000,1470.000000,4.791000e+03,1954.000000,1.120000,3.361650e+05,4.617000e+05,2191.000000,45.434004,-122.806095,2.000000,0.000000,1.000000,0.000000,1.000000,0.000000
50%,5.220000e+05,3.000000,3.000000,1996.000000,6.969000e+03,1981.000000,1.120000,4.263300e+05,5.737000e+05,2545.000000,45.488914,-122.674080,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
75%,6.622000e+05,4.000000,3.000000,2653.000000,9.147000e+03,2003.000000,1.130000,5.524900e+05,7.095000e+05,3099.000000,45.526348,-122.592571,2.000000,0.000000,1.000000,1.000000,1.000000,0.000000
max,4.100000e+07,43.000000,23.000000,51290.000000,2.087221e+08,2021.000000,1.130000,9.500545e+07,6.537500e+06,27029.000000,45.713860,-122.280975,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [20]:
df['homeType'].unique() # ...?!

<StringArray>
['TOWNHOUSE', 'SINGLE_FAMILY', 'APARTMENT', 'CONDO', 'HOME_TYPE_UNKNOWN']
Length: 5, dtype: str

In [19]:
df.to_csv("cleaned_housing.csv", index=False)